export const sdata = [
   {
    key:1,
    img:"assets/TopPicks/first.jpg",
    price:"220",
    name:"item1",
    catagory:"topPicks"
   },
   {
    key:1,
    img:"assets/TopPicks/first.jpg",
    price:"121",
    name:"item2",
    catagory:"topPicks"
   },
   {
    key:1,
    img:"assets/TopPicks/first.jpg",
    price:"223",
    name:"item3",
    catagory:"topPicks"
   },
   {
    key:1,
    img:"assets/TopPicks/first.jpg",
    price:"555",
    name:"item4",
    catagory:"topPicks"
   },
   {
    key:1,
    img:"assets/TopPicks/first.jpg",
    price:"665",
    name:"item5",
    catagory:"topPicks"
   },
   {
    key:1,
    img:"assets/TopPicks/first.jpg",
    price:"55",
    name:"item6",
    catagory:"topPicks"
   },
   {
    key:1,
    img:"assets/TopPicks/first.jpg",
    price:"655",
    name:"item7",
    catagory:"topPicks"
   }

]